add test timeout routines and tweak keep-alives

diff --git a/qqX.builtins/freebird/qqX_quickGet_mods b/qqX.builtins/freebird/qqX_quickGet_mods
--- a/qqX.builtins/freebird/qqX_quickGet_mods
+++ b/qqX.builtins/freebird/qqX_quickGet_mods
@@ -266,10 +266,13 @@ function editions_anduinos {
             if [[ $RELEASE == "LTS" ]]; then ReleaseNumber="$(web_pipe "https://docs.anduinos.com/VERSIONS.html" |tr '>' '\n' | grep '</td' | grep LTS | fv -M -Q)"
             else ReleaseNumber="$(web_pipe "https://docs.anduinos.com/VERSIONS.html" |tr '>' '\n' | grep '</td' | grep -v LTS | fv -M -Q)"
             fi
+            [[ ! $ReleaseNumber ]] && break
             ReleasePoint="$(web_pipe "https://download.anduinos.com/${ReleaseNumber}/" | grep href | fv -M -Q )"
+            [[ ! $ReleasePoint ]] && break
             ReleaseEditions="$(web_pipe "https://download.anduinos.com/${ReleaseNumber}/${ReleasePoint}" \
             | grep -v sha256 | grep -v torrent | tr '>' '\n' | grep iso | grep -v '<a' | cut -d'<' -f1 | cut -d'-' -f3 | cut -d'.' -f1 | paste -s -d' ')"
             printf "\nReleaseName=\"%s\"\nReleaseNumber=\"%s\"\nReleasePoint=\"%s\"\nReleaseEditions=\"%s\"" "$RELEASE" "$ReleaseNumber" "$ReleasePoint" "$ReleaseEditions" > "$ReleaseDataLog"
+            [[ ! $ReleaseEditions ]] && break
             sleep 1
         fi
         ReleaseName= ; ReleaseNumber= ; ReleasePoint= ; ReleaseEditions=
@@ -281,6 +284,7 @@ function editions_anduinos {
     printf "%s" "$RELEASE" > "$EditionsDataLog"
     printf "" > "$GetDataLog"
     [[ ! $ReleaseEditions ]] && source "$ReleaseDataLog"
+    [[ ! $ReleaseEditions ]] && return 1
     echo "$ReleaseEditions"
 }
 function get_anduinos {
@@ -1356,16 +1360,16 @@ function validate_release() {
 # Download a SMALL file page, checksum etc from the web and pipe it to stdout  (not to confuse with 'web_get')
 function web_pipe {
     local Args=("${@}") ; [[ ! "${Args[*]}" ]] && return 1
-    if ! curl --disable -sLf --retry 8 --retry-max-time 4 --connect-timeout 4 --no-keepalive --max-time 30 "${Args[@]}"; then
-        curl --disable -sLf --retry 6 --retry-max-time 6 --connect-timeout 6 --no-keepalive --max-time 30 "${Args[@]}"
+    if ! curl --disable -sLf --retry 8 --retry-max-time 4 --connect-timeout 4 --keepalive-time 2 --location-trusted --max-time 20 "${Args[@]}"; then
+        curl --disable -sLf --retry 6 --retry-max-time 6 --connect-timeout 6  --location-trusted  --max-time 30 "${Args[@]}"
     fi
 }
 
 # Download a JSON file from the web and pipe it to stdout
 function web_pipe_json {
     local Args=("${@}") ; [[ ! "${Args[*]}" ]] && return 1
-    if ! curl --disable -sLf --retry 8 --retry-max-time 4 --connect-timeout 4 --no-keepalive --max-time 30 --header "Accept: application/json" "${Args[@]}"; then
-        curl --disable -sLf --retry 6 --retry-max-time 6 --connect-timeout 6 --no-keepalive --max-time 30 --header "Accept: application/json" "${Args[@]}"
+    if ! curl --disable -sLf --retry 8 --retry-max-time 4 --connect-timeout 4 --keepalive-time 2 --location-trusted --max-time 20 --header "Accept: application/json" "${Args[@]}"; then
+        curl --disable -sLf --retry 6 --retry-max-time 6 --connect-timeout 6  --location-trusted --max-time 30 --header "Accept: application/json" "${Args[@]}"
     fi
 }
 
@@ -1380,16 +1384,17 @@ function check_pipe {
         fi
         return 1
     fi
-    curl --disable -sLf --head --retry 16 --retry-max-time 2 --connect-timeout 2 --no-keepalive --location-trusted --max-time 30 "${Args[@]}" > "/tmp/qGet_check_pipe.txt"
+    curl --disable -sLf --head --retry 16 --retry-max-time 2 --connect-timeout 2  --location-trusted --max-time 30 "${Args[@]}" > "/tmp/qGet_check_pipe.txt"
     if ! grep -si 'HTTP/' "/tmp/qGet_check_pipe.txt" | tail -n 1 | grep -q 200; then
         printf "" > "/tmp/qGet_check_pipe.txt"
-        curl --disable -sLf --head --retry 8 --retry-max-time 4 --connect-timeout 4 --no-keepalive --location-trusted --max-time 30 "${Args[@]}" > "/tmp/qGet_check_pipe.txt"
+        curl --disable -sLf --head --retry 8 --retry-max-time 4 --connect-timeout 4 --keepalive-time 2 --location-trusted --max-time 30 "${Args[@]}" > "/tmp/qGet_check_pipe.txt"
     fi
     if grep -si 'HTTP/' "/tmp/qGet_check_pipe.txt" | tail -n 1 | grep -q 200; then return 0 ; else return 1 ; fi
 }
 # where HTTP/ 200 = success (with size data etc as readable) and 404 = not found = fail
 # --location-trusted means extend secure connection to the mirror or to the CDN otherwise 302 redirects will lose https.
 # --no-keepalive/--keepalive-time as we don't need much, and so we then move on cleanly and can drop any cookies, if possible
+# REVIEW  no-keepalive can possibly clash with location-trusted
 
 ## TWEAK
 # Check if a URL needs to be redirected and returns the final URL mirror or CDN
@@ -1491,12 +1496,12 @@ function web_check {
     printf "%s" "$URL" > "/tmp/qmod-dl-url"
     if [[ ! $URL ]]; then
         if [[ $ChkLog ]] && ! grep -qs 'ERROR: No URL' "$ChkLog" ; then
-            printf "\nERROR: No URL > Possible initial lookup or server problem\n" >> "$ChkLog"
+            printf "ERROR: No URL > Possible initial lookup or server problem\n\n" >> "$ChkLog"
         fi
         return 1
     elif [[ "$(basename "$URL")" != *.* ]] && [[ "$(basename "$URL")" != *SUMS* ]]; then
         if [[ $ChkLog ]] && ! grep -qs 'Non Conformant URL' "$ChkLog" ; then
-            printf "\nERROR: Non Conformant URL > Possible initial lookup or server problem \n" >> "$ChkLog"
+            printf "ERROR: Non Conformant URL > Possible initial lookup or server problem \n\n" >> "$ChkLog"
         fi
         return 1
     fi
@@ -1551,7 +1556,7 @@ function test_all {
         if [[ ! $OS ]]; then printf "\nTest All - Missing OS data: FAIL\n\n"
         else printf "\nOS > %s:\n\n" "${OS^^}"
         fi
-        } >> "$ChkLog"
+        } | tee -a "$ChkLog"
     fi
     [[ ! $OS ]] && return
 
@@ -1559,14 +1564,32 @@ function test_all {
     [[ "${OS}" == *ubuntu* ]] && [[ "${OS}" != "ubuntu-server" ]] &&  FUNC="ubuntu"
 
     if [[ $(type -t "releases_${FUNC}") == function ]]; then
+        SECONDS=0
         for RELEASE in $("releases_${FUNC}"); do
+            if [[ ! $RELEASE ]] && [[ $SECONDS -gt 60 ]]; then
+                printf "ERROR: %-40s  >  Releases function FAIL \n" "$OS" | tee -a "$ChkLog"
+                return 1
+            fi
+            SECONDS=0
             if [[ $(type -t "editions_${FUNC}") == function ]]; then
                 for EDITION in $(editions_"${OS}"); do
                     # 'get_$OS' should output two args; a filepath URL, followed a checksum number
                     #  but additionally add mirror URL, if available or possible, to check the state of the mirror service,
                     #  noting that mirrors can block in the time gap between the location of a mirror URL and testing it.
-                    GetLine=$(get_"${OS}" "$RELEASE")
-                    printf "%s" "$GetLine" > "/tmp/qGet-test-all-GetLine.txt"
+                    if [[ ! $EDITION ]] && [[ $SECONDS -gt 60 ]]; then
+                        printf "ERROR: %s  %-12s  >  Editions function FAIL \n" "$OS" "$RELEASE" | tee -a "$ChkLog"
+                        return 1
+                    fi
+                    printf "" > "/tmp/qGet-test-all-GetLine.txt"
+                    SECONDS=0
+                    while [[ $SECONDS -lt 60 ]] && [[ ! $(cat "/tmp/qGet-test-all-GetLine.txt") ]] ; do
+                        GetLine=$(get_"${OS}" "$RELEASE")
+                        printf "%s" "$GetLine" > "/tmp/qGet-test-all-GetLine.txt"
+                    done
+                    if [[ ! $(cat "/tmp/qGet-test-all-GetLine.txt") ]]; then
+                        printf "ERROR: %s  %-12s  >  Get function FAIL \n" "$OS" "$RELEASE" | tee -a "$ChkLog"
+                        return 1
+                    fi
                     URL=$(tr -cd '[:print:]' <<< "$GetLine" | awk '{print $1}')
                     [[ ! $URL ]] && printf "\nERROR: No URL from function %s\n" "get_${OS} $RELEASE"
                     [[ $CheckMirrors ]] &&  URL=$(web_redirect "${URL}")
@@ -1580,9 +1603,10 @@ function test_all {
                         else test_result "${OS}" "${RELEASE}" "${EDITION}" "${URL}" "${CHECK}" "$HASH"
                         fi
                     fi
+                    SECONDS=0
                 done
                 if [[ ! $EDITION ]] && [[ $ChkLog ]] && ! grep -qs "$OS" <<< "$(grep -s 'Editions function FAIL' "$ChkLog")" ; then
-                    printf "ERROR: %s  %-40s  >  Editions function FAIL \n" "$OS" "$RELEASE" >> "$ChkLog"
+                    printf "ERROR: %s  %-12s  >  Editions function FAIL \n" "$OS" "$RELEASE" | tee -a "$ChkLog"
                 fi
             elif [[ "${OS}" == "windows"* ]]; then
                 # Caution with current Quickemu, --check windows with $2 (or/and $3) will trigger a windows download
@@ -1607,8 +1631,16 @@ function test_all {
                     [[ ! $URL ]] && printf "\nERROR: No URL from function %s\n" "get_${OS}"
                     test_result "${OS}" "${RELEASE}" "${EDITION}" "${URL}"
                 elif [ "${OPERATION}" == "test" ]; then
-                    GetLine=$(get_"${OS}" "$RELEASE")
-                    printf "%s" "$GetLine" > "/tmp/qGet-test-all-GetLine.txt"
+                    printf "" > "/tmp/qGet-test-all-GetLine.txt"
+                    SECONDS=0
+                    while [[ $SECONDS -lt 60 ]] && [[ ! $(cat "/tmp/qGet-test-all-GetLine.txt") ]] ; do
+                        GetLine=$(get_"${OS}" "$RELEASE")
+                        printf "%s" "$GetLine" > "/tmp/qGet-test-all-GetLine.txt"
+                    done
+                    if [[ ! $(cat "/tmp/qGet-test-all-GetLine.txt") ]]; then
+                        printf "ERROR: %s  %-12s  >  Get function FAIL \n" "$OS" "$RELEASE" | tee -a "$ChkLog"
+                        return 1
+                    fi
                     URL=$(tr -cd '[:print:]' <<< "$GetLine" | awk '{print $1}')
                     [[ ! $URL ]] && printf "\nERROR: No URL from function %s\n" "get_${OS} $RELEASE"
                     [[ $CheckMirrors ]] &&  URL=$(web_redirect "${URL}")
@@ -1619,6 +1651,7 @@ function test_all {
                     fi
                 fi
             fi
+            SECONDS=0
         done
         if [[ ! $RELEASE ]] && [[ $ChkLog ]] && ! grep -qs "$OS  >  Releases function FAIL" "$ChkLog" ; then
             printf "ERROR: %s  >  Releases function FAIL \n"  "$OS"  >> "$ChkLog"
