curl parallel - part one

diff --git a/qqX.builtins/freespirit/qqX_quickget_mods b/qqX.builtins/freespirit/qqX_quickget_mods
--- a/qqX.builtins/freespirit/qqX_quickget_mods
+++ b/qqX.builtins/freespirit/qqX_quickget_mods
@@ -870,27 +870,31 @@ function web_get() {
     if [ "${DIR}" != "$(pwd)" ] && ! mkdir -p "${DIR}" 2>/dev/null; then
         echo "ERROR: Unable to create directory ${DIR}" ; exit 1
     fi
-    #  Allow qqX or any external process to pick up the FINALIZED NAME
+    #  Allow qqX or any external process to pick up the FINALIZED VM-NAME
     # - avoids overwrites eg windows 'unattended'
     # - external proc should clear this file before starting so the grep test will function
     if ! grep -sq 'New_VM_InstanceName' "/tmp/qe_new_vm_name.txt" ; then
         printf "New_VM_InstanceName=\"%s\" \n" "$(basename "$DIR")" > "/tmp/qe_new_vm_name.txt"
     fi
     if [[ ${OS} != windows && ${OS} != macos && ${OS} != windows-server ]]; then
-        echo "Downloading $(pretty_name "${OS}") ${RELEASE} ${EDITION}"
-        echo "- URL: ${URL}"
+        echo "Downloading $(pretty_name "${OS}") ${RELEASE} ${EDITION}" ; echo "- URL: ${URL}"
     fi
     # Add retries to the standard Quickemu 4.9.x method:
     # --continue-at -  will continue/resume a previous file transfer but we need to make sure we actually have a connection to start with ...
-    tput civis
-    if ! curl --disable -Lf --retry 6 --retry-max-time 3 --retry-delay 1 --progress-bar --continue-at - --output "${DIR}/${FILE}" \
-    --user-agent "${USER_AGENT}" "${HEADERS[@]}" -- "${URL}"; then
+    tput civis ; echo
+    local CurlParallel=
+    Curl_NoPara=1 # Freespirit only, for moment. Plus TODO toggle
+    if [[ ! $Curl_NoPara ]] && grep -qs -e '--parallel' <<< "$(curl --help all)" ; then
+        CurlParallel="--parallel" ; printf "\n\n  Multiplexed parallel download: \n\n"
+    fi
+    if ! curl --disable -Lf "$CurlParallel" --retry 500 --retry-connrefused --retry-max-time 3 --retry-delay 1 --progress-bar --continue-at - \
+    --output "${DIR}/${FILE}" --user-agent "${USER_AGENT}" "${HEADERS[@]}" -- "${URL}"; then
         # qqX needs to take control here, use exit instead
         if pgrep qqX >/dev/null ; then echo ; tput cnorm ; exit
-        else echo "ERROR: Failed to download ${URL} with curl." ; tput cnorm ; rm -f "${DIR}/${FILE}"
+        else echo "ERROR: Failed to download ${URL} with curl." ; tput cnorm ; echo ; rm -f "${DIR}/${FILE}"
         fi
     fi
-    tput cnorm
+    tput cnorm ; echo
 }
 
 
